### ISSUE TITLE
New demo theme

### ISSUE THREAD

**Issue by kyrapieterse** [maxi-blocks/maxiblocks-demo-theme#1]
![image](https://github.com/user-attachments/assets/aed01e14-1d42-48c7-96ea-f5c6be52663d)

This is for new patterns and pages for a sample https://maxiblocks.com/demo/theme/block-pattern-blog-hero/bhol-pro-01/

- [ ] Need to upload all the Author, Archive pages etc here
- [ ] Need to move the 404 pages here
- [ ] Need to move the navigation menus here

Not sure about footers?

Also this tab should be the default when in the FSE editor when the cloud is launched

**Comment by elzadj** [comment]
Good idea, let me see how we can do it, maybe with a tag, or a dedicated category. Then we can add footers and whatever. But plugin and the demo UI need updates 100%.

**Comment by elzadj** [comment]
Ok, we can do the same that we did with Playground by using type "Theme" or "Site editor". But then these patterns are not going to be shown in other tabs. If we need them in 2 tabs, need to figure something else (a tag, most likely). Navigation and Footers are the main concern here.

**Comment by kyrapieterse** [comment]
if its easier then we can just have the nav and footer under the theme - people will know to look there if they need a different footer or nav somewhere else

**Comment by kyrapieterse** [comment]
**Pages Category** Parent is "Theme"	

404
Blog Index
Blog Single
Tag Archive
Search Results
Category Archive
Date Archive
Custom Taxonomy Archive
Author Archive
All Archive Page

**Patterns - Category** Parent is "Theme"	(slug is /wordpress-themes/ )

Author Box - https://maxiblocks.com/demo/wordpress-themes/block-patterns-author-box/arbl-pro-01/
Mega menu
Navigation menu
Blog hero
Blog stories - https://maxiblocks.com/demo/wordpress-themes/block-patterns-blog-stories/bsl-pro-01/
Blog comments
Pagination

**Comment by ckp267** [comment]
For reference @elzadj after our meeting on 16/08/2024

**URL structure and naming convention**

The outcome of our meeting is that we need to test how we can implement custom taxonomies on /demo/ to create archive pages with the site editor.

**Normal patterns** (see archive page design attached by designer Kyra)
- Archive for "block pattern woocommerce": https://maxiblocks.com/demo/block-pattern-woocommerce/
- https://maxiblocks.com/demo/block-pattern-woocommerce/wcl-pro-01/
- https://maxiblocks.com/demo/block-pattern-woocommerce/wcd-pro-01/

**Theme patterns**
- https://maxiblocks.com/demo/wordpress-themes/block-patterns-author-box/
- https://maxiblocks.com/demo/wordpress-themes/block-patterns-author-box/arbl-pro-01/
- https://maxiblocks.com/demo/wordpress-themes/block-patterns-author-box/arbd-pro-01/

**Pages**
- https://maxiblocks.com/demo/website-templates/accountant-pages/
- https://maxiblocks.com/demo/website-templates/accountant-pages/apt-pro-01/

**Theme pages**
- https://maxiblocks.com/demo/wordpress-themes/blog-single-pages/
- https://maxiblocks.com/demo/wordpress-themes/blog-single-pages/bgsp-pro-01/

**Tags**
- Free
- Pro

**NOTE:** I would like tags to be used for alternative searching or browsing, such as expanding topics (Restaurants, Bars, Architecture) or features like "Video Maxi", "Accordion Maxi", "Interaction Builder", "Shape mask", and "Buttons".

**Question:**
1. Can we use Typesense to return results for text inside patterns or pages? The idea is to get more relevant search results, which could also improve when we upgrade Typesense to the current version in the coming months.

![archieve pages copy](https://github.com/user-attachments/assets/01856f78-64c2-4561-a02a-2bd42200e3ba)

**Comment by elzadj** [comment]
- [x] Updates to staging demo
- [x] New tab "Theme" for the new gutenberg_type
- [x] Change the theme on staging demo to a block theme with a working Site Editor
- [x] Make changes into the editor Maxi Demo plugin we use for importing patterns from the demo to the library site
- [x] Figure out the url structure and functions to rewrite url.
- [ ] ~~Redirect? Rewrite urls on lib site for the re-index?~~
- [x] Add all fields we need for the taxonomy: description with html, seo header, subheader.
- [x] Breadcrumbs.
- [x] Get the featured image info from the external site. Should work as a function we can run on live later.
- [x] New template for the taxonomy archive.
- [x] New template for the single post.
- [x] Hide header, footer, etc. in iframes for single posts.
- [x] Tags template.
- [x] Script that removes links from the posts works for all links in the template, need to fix it.
- [x] Figure out Rank Math SEO for taxonomy.
- [x] Add content from .txt files (?)

**Comment by elzadj** [comment]
> Can we use Typesense to return results for text inside patterns or pages? 

You mean search by the pattern's content too? Yes, we can add it to both, the plugin and the demo code. It's going to be the whole Gutenberg code tho, not just the text from there.

This is what we have now for the search: ```post_title, post_number, category.lvl0, category.lvl1, cost```

**Comment by elzadj** [comment]
Steps to update demo site:

- [x] Backups!
- [x] Remove all zip files, log files, etc.
- [x] Remove redundant themes (maybe keep 2024 just in case)
- [x] Update WP
- [x] Update MaxiBlocks plugin
- [x] Update other plugins
- [x] Install new DLE plugin.
- [x] Install FIFU and run the script to get the external images as featured images for posts. You can go with bunches by 1000 post (the default), do it until you see that 0 posts were updated in the debug.log. 
_Posts that need the FI updated manually_: playground pattern 3, playground pattern 4, BSP-PRO-02-2, ARCP-PRO-01, HOL-PRO-52, HOD-PRO-52, HORPT-PRO-01, IND-PRO-23, PTMD-PRO-54, PTML-PRO-54, HOD-PRO-237, HOL-PRO-237, HOD-PRO-217, HOL-PRO-217, HOL-05, HEL-23
- [x] Regenerate FIFU metadata in the plugin's settings.
- [x] Update (unzip) new versions for the theme, and frontend search.
- [x] Update everything else that have updates.
- [x] Install ACF, add the description field, show it on backend
- [x] Enable Rank Math SEO breadcrumbs.
- [x] Move the templates from the staging to live. Re-upload images.
- [x] Get all the featured images with scripts.
- [x] Generate and add all .txt files for description.
- [x] Generate the descriptions using the scripts.
- [ ] Make sure it all works as we want. 
- [ ] Rank Math SEO settings for taxonomies, categories, posts, etc.
- [ ] Open the site for indexing when we are ready.

**Comment by elzadj** [comment]
> > Can we use Typesense to return results for text inside patterns or pages?
> 
> You mean search by the pattern's content too? Yes, we can add it to both, the plugin and the demo code. It's going to be the whole Gutenberg code tho, not just the text from there.
> 
> This is what we have now for the search: `post_title, post_number, category.lvl0, category.lvl1, cost`

I suggest we try `post_title, post_number, category.lvl0, category.lvl1, post_tag, gutenberg_code, cost`

**Comment by elzadj** [comment]
> URL structure and naming convention

It's not really possible to have the same structure for taxonomy and posts inside that taxonomy on wordpress, so I suggest this:

maxiblocks.com/demo/**wordpress**/**patterns**/block-pattern-text/headline/ for the taxonomy
maxiblocks.com/demo/**patterns**/block-pattern-text/headline/hed-30/  for the posts in that taxonomy 

maxiblocks.com/demo/**wordpress**/**themes**/block-patterns-author-box/
maxiblocks.com/demo/**themes**/block-patterns-author-box/arbl-pro-01/

maxiblocks.com/demo/**wordpress**/**website-templates**/accountant-pages/
maxiblocks.com/demo/**website-templates**/accountant-pages/apt-pro-01/


**OR**
maxiblocks.com/demo/**wordpress**/**wordpress-patterns**/block-pattern-text/headline/ for the taxonomy
maxiblocks.com/demo/**wordpress-patterns**/block-pattern-text/headline/hed-30/  for the posts in that taxonomy 

maxiblocks.com/demo/**wordpress**/**wordpress-themes**/block-patterns-author-box/
maxiblocks.com/demo/**wordpress-themes**/block-patterns-author-box/arbl-pro-01/

maxiblocks.com/demo/**wordpress**/**website-templates**/accountant-pages/
maxiblocks.com/demo/**website-templates**/accountant-pages/apt-pro-01/

We can change the base url part for the taxonomy (**wordpress** now) to whatever you want, but the point is - we need it there. Can't make it empty.

**Comment by ckp267** [comment]
@elzadj 

This format please. Because we get better keywords in the URL specially for the 2000 plus patterns. 

maxiblocks.com/demo/**wordpress**/**wordpress-patterns**/block-pattern-text/headline/ for the taxonomy
maxiblocks.com/demo/**wordpress-patterns**/block-pattern-text/headline/hed-30/  for the posts in that taxonomy 

maxiblocks.com/demo/**wordpress**/**wordpress-themes**/block-patterns-author-box/
maxiblocks.com/demo/**wordpress-themes**/block-patterns-author-box/arbl-pro-01/

maxiblocks.com/demo/**wordpress**/**website-templates**/accountant-pages/
maxiblocks.com/demo/**website-templates**/accountant-pages/apt-pro-01/
